#ifndef _GROUPS_H
#define _GROUPS_H

/* ===================================================================== *
 *                         EVENT GROUP DEFINITIONS                       *
 * ===================================================================== */

#define GROUP_CAN_PAYLOAD_BIT(x) x - CAN_HEADER_PAYLOAD_BASE
#define GROUP_CAN_PAYLOAD_BARO1  GROUP_CAN_PAYLOAD_BIT(CAN_HEADER_PAYLOAD_BARO1)
#define GROUP_CAN_PAYLOAD_BARO2  GROUP_CAN_PAYLOAD_BIT(CAN_HEADER_PAYLOAD_BARO2)
#define GROUP_CAN_PAYLOAD_ACCEL  GROUP_CAN_PAYLOAD_BIT(CAN_HEADER_PAYLOAD_ACCEL)
#define GROUP_CAN_PAYLOAD_STATUS GROUP_CAN_PAYLOAD_BIT(CAN_HEADER_PAYLOAD_STATUS)
#define GROUP_CAN_PAYLOAD_RDY 	 0x80

#define GROUP_MESSAGE_READY_LORA  0x01
#define GROUP_MESSAGE_READY_USB   0x02

#define GROUP_TASK_ENABLE_FLASH   0x01
#define GROUP_TASK_ENABLE_HIGHRES 0x02
#define GROUP_TASK_ENABLE_LOWRES  0x04
#define GROUP_TASK_ENABLE_LORA    0x08
#define GROUP_TASK_ENABLE_IDLE    0x80

#define GROUP_SYSTEM_STATUS_PAYLOAD	 	 0x08
#define GROUP_SYSTEM_STATUS_AEROBRAKES 0x10

#endif
