var annotated_dup =
[
    [ "A3G4250D", "structA3G4250D.html", "structA3G4250D" ],
    [ "BMP581", "structBMP581.html", null ],
    [ "CAN_RX_data", "group__CAN__Interface.html#structCAN__RX__data", null ],
    [ "ctxFlashBuffer", "structctxFlashBuffer.html", null ],
    [ "ctxHDataAcquisition", "structctxHDataAcquisition.html", null ],
    [ "ctxIdle", "structctxIdle.html", null ],
    [ "ctxLDataAcquisition", "structctxLDataAcquisition.html", null ],
    [ "ctxLoRaSample", "structctxLoRaSample.html", null ],
    [ "ctxLoRaTransmit", "structctxLoRaTransmit.html", null ],
    [ "ctxState", "structctxState.html", null ],
    [ "ctxStateUpdate", "structctxStateUpdate.html", null ],
    [ "ctxUsbReceive", "structctxUsbReceive.html", null ],
    [ "ctxUsbTransmit", "structctxUsbTransmit.html", null ],
    [ "DeviceHandle_t", "structDeviceHandle__t.html", null ],
    [ "Flash", "structFlash.html", "structFlash" ],
    [ "GPS", "group__GPS.html#structGPS", null ],
    [ "GPS_Data", "group__GPS.html#structGPS__Data", null ],
    [ "Handles", "structHandles.html", null ],
    [ "KX134_1211", "structKX134__1211.html", "structKX134__1211" ],
    [ "LoRa", "structLoRa.html", "structLoRa" ],
    [ "LoRa_Packet", "group__LoRa.html#structLoRa__Packet", "group__LoRa_structLoRa__Packet" ],
    [ "Shell", "shell_8h.html#structShell", null ],
    [ "ShellProgramHandle_t", "shell_8h.html#structShellProgramHandle__t", null ],
    [ "ShellTaskParams", "shell_8h.html#structShellTaskParams", null ],
    [ "SPI", "structSPI.html", "structSPI" ],
    [ "StateHandle_t", "structStateHandle__t.html", null ],
    [ "UART", "group__UART__Interface.html#structUART", "group__UART__Interface_structUART" ],
    [ "UART_Pins", "group__UART__Interface.html#structUART__Pins", null ]
];