var annotated_dup =
[
    [ "A3G4250D_t", "structA3G4250D__t.html", "structA3G4250D__t" ],
    [ "BMP581_t", "structBMP581__t.html", null ],
    [ "CAN_RX_data", "group__CAN__Interface.html#structCAN__RX__data", null ],
    [ "ctxFlashBuffer", "structctxFlashBuffer.html", null ],
    [ "ctxIdle", "structctxIdle.html", null ],
    [ "ctxState", "structctxState.html", null ],
    [ "ctxStateUpdate", "structctxStateUpdate.html", null ],
    [ "DeviceHandle_t", "group__Device__Management.html#structDeviceHandle__t", null ],
    [ "GPS_Data", "group__GPS.html#structGPS__Data", null ],
    [ "Handles", "structHandles.html", null ],
    [ "KX134_1211_t", "structKX134__1211__t.html", "structKX134__1211__t" ],
    [ "SAM_M10Q_t", "group__GPS.html#structSAM__M10Q__t", null ],
    [ "Shell", "group__Shell.html#structShell", null ],
    [ "ShellProgramHandle_t", "group__Shell.html#structShellProgramHandle__t", null ],
    [ "ShellTaskParams", "group__Shell.html#structShellTaskParams", null ],
    [ "SPI", "structSPI.html", "structSPI" ],
    [ "StateHandle_t", "structStateHandle__t.html", null ],
    [ "SX1272_Packet", "group__SX1272.html#structSX1272__Packet", "group__SX1272_structSX1272__Packet" ],
    [ "SX1272_t", "structSX1272__t.html", "structSX1272__t" ],
    [ "UART_Pins", "group__UART__Interface.html#structUART__Pins", null ],
    [ "UART_t", "group__UART__Interface.html#structUART__t", "group__UART__Interface_structUART__t" ],
    [ "W25Q128_t", "structW25Q128__t.html", "structW25Q128__t" ]
];