var hierarchy =
[
    [ "Accel_t", "group__API__accel.html#structAccel__t", null ],
    [ "ADC_Config", "group__ADC__Interface.html#structADC__Config", null ],
    [ "ADC_t", "group__ADC__Interface.html#structADC__t", null ],
    [ "ArgParser", "structArgParser.html", null ],
    [ "Argument", "structArgument.html", null ],
    [ "Baro_t", "group__API__baro.html#structBaro__t", null ],
    [ "CAN_Config", "structCAN__Config.html", null ],
    [ "CAN_Data", "structCAN__Data.html", null ],
    [ "CAN_t", "structCAN__t.html", null ],
    [ "DeviceHandle_t", "group__Device__Management.html#structDeviceHandle__t", null ],
    [ "Error", "structError.html", null ],
    [ "ExclusionGroup", "structExclusionGroup.html", null ],
    [ "Field", "packet_8h.html#structField", null ],
    [ "Flash_t", "group__API__flash.html#structFlash__t", null ],
    [ "GPIO_Config", "group__GPIO__Pin.html#structGPIO__Config", null ],
    [ "GPIOpin_t", "group__GPIO__Pin.html#structGPIOpin__t", null ],
    [ "Gyro_t", "group__API__gyro.html#structGyro__t", null ],
    [ "KX134_1211_t", "group__Accelerometer__KX134__1211.html#structKX134__1211__t", null ],
    [ "LoRa_t", "group__API__LoRa.html#structLoRa__t", null ],
    [ "Message", "topic_8h.html#structMessage", null ],
    [ "Packet", "packet_8h.html#structPacket", null ],
    [ "PrivateTopic", "__topic_8h.html#structPrivateTopic", null ],
    [ "SAM_M10Q_Data", "group__GPS.html#structSAM__M10Q__Data", null ],
    [ "SAM_M10Q_t", "group__GPS.html#structSAM__M10Q__t", null ],
    [ "ShellProgramHandle_t", "group__Shell.html#structShellProgramHandle__t", null ],
    [ "SPI", null, [
      [ "A3G4250D_t", "structA3G4250D__t.html", null ],
      [ "AIS3624DQ_t", "structAIS3624DQ__t.html", null ],
      [ "BMP581_t", "structBMP581__t.html", null ],
      [ "IAM_20380_t", "structIAM__20380__t.html", null ],
      [ "LPS22DF_t", "structLPS22DF__t.html", null ]
    ] ],
    [ "SPI_Config", "group__SPI__Interface.html#structSPI__Config", null ],
    [ "SPI_t", "group__SPI__Interface.html#structSPI__t", null ],
    [ "State", "group__State.html#structState", null ],
    [ "SX1272_Config", "group__SX1272.html#structSX1272__Config", null ],
    [ "SX1272_t", "group__SX1272.html#structSX1272__t", null ],
    [ "TIM_CCMR_Output", "group__TIM__Interface.html#structTIM__CCMR__Output", null ],
    [ "TIM_Config", "group__TIM__Interface.html#structTIM__Config", null ],
    [ "TIM_t", "group__TIM__Interface.html#structTIM__t", null ],
    [ "Topic", "topic_8h.html#structTopic", null ],
    [ "UART_Config", "group__UART__Interface.html#structUART__Config", null ],
    [ "UART_t", "group__UART__Interface.html#structUART__t", null ],
    [ "W25Q128_t", "group__W25Q128.html#structW25Q128__t", null ]
];